### ISSUE TITLE
Error: System error: exec: "bash": executable file not found in $PATH

### ISSUE THREAD

**Issue by YuzhongHuangCS** [openSUSE/docker-containers#13] opened 2016-03-15 06:08 UTC
I found that `harlequin` and `leap` release of the docker image is severely broken and failed to run any command like `bash`, `pwd`.
Only `tumbleweed` release is working. 
##  Console output below

```
hyz@Aspire:~$ docker run -i opensuse:leap bash
exec: "bash": executable file not found in $PATH
Error response from daemon: Cannot start container 91fccbf852b4884e4e5aeb38c577d16fb968eaf070c6fd2a33f9a1541b941e7f: [8] System error: exec: "bash": executable file not found in $PATH
```

```
hyz@Aspire:~$ docker run -i opensuse:leap pwd
exec: "pwd": executable file not found in $PATH
Error response from daemon: Cannot start container a254f472e2cb7836b1ca6969d6f9a12ad548e497d033a409af1224791f0a388c: [8] System error: exec: "pwd": executable file not found in $PATH
```

**Comment by flavio** [comment] 2016-03-15 08:17
This has been caused by a bug on the build system of the Docker Hub (see [this](https://github.com/docker-library/official-images/pull/1537#issuecomment-196652045) issue).

We reported the issue to upstream, in the meantime we will push the images to the `opensuse/` namespace on the Docker Hub

**Comment by cyphar** [comment] 2016-03-15 10:20
As @flavio said, the build system for the official images on the Docker Hub appears to be having some problems. We've pushed the images to the `opensuse/` namespace with the form `opensuse/amd64:<version>`. Sorry for the inconvenience.

If you have any images that are derived on `library/opensuse` (`FROM opensuse:<tag>`) then you can fix those as well by creating those tags like so:

```
% docker tag opensuse/amd64:leap opensuse:leap
```

**Comment by tianon** [comment] 2016-03-15 15:20
We've also re-pushed the older tags to `opensuse:` while we investigate what we can do to fix this. :cry:

**Comment by tboerger** [comment] 2016-12-21 08:43
```
# docker run -ti opensuse:leap bash
Unable to find image 'opensuse:leap' locally
leap: Pulling from library/opensuse
Digest: sha256:8c49cb12499ba72f02791d6db3519a196aa3d9e8f485d3307c275eff9603c8ab
Status: Downloaded newer image for opensuse:leap
bash-4.3#
```

Seems to be fixed, closing.

**Closed as completed by tboerger** 2016-12-21 08:43 UTC
