### ISSUE TITLE
Tumbleweed repo actions broken after few days in docker

### ISSUE THREAD

**Issue by realknorke** [openSUSE/docker-containers#57] opened 2017-05-15 07:23 UTC
I have a simple Dockerfile

> FROM opensuse:tumbleweed
> ARG GIT_COMMIT=unknown
> LABEL git-commit=$GIT_COMMIT
> CMD ["sleep", "600"]

I can use this for creating an image. REFRESHing repo metadata using zypper works. Installing packages works too.

After a few days (5+?) I cannot install any package, e.g. "tree".

>The following NEW package is going to be installed:
>  tree
>1 new package to install.
>Overall download size: 53.8 KiB. Already cached: 0 B. After the operation, additional 105.7 KiB will be used.
>Continue? [y/n/...? shows all options] (y): 
>Retrieving package tree-1.7.0-3.10.x86_64                                                                                                                                                                 >(1/1),  53.8 KiB (105.7 KiB unpacked)
>Media source 'http://download.opensuse.org/tumbleweed/repo/oss/' does not contain the desired medium
>Abort, retry, ignore? [a/r/i/...? shows all options] (a): r
>Retrieving: tree-1.7.0-3.10.x86_64.rpm >....................[done]
>Checking for file conflicts: >.........................................[done]
>(1/1) Installing: tree-1.7.0-3.10.x86_64 >..............................[done]

As you can see a RETRY is working here. But this is not always the case! (and as I have to use the "--non-interactive" setting of zypper even the RETRY is not a solution)

The error is always the same: Media source 'http://download.opensuse.org/tumbleweed/repo/oss/' does not contain the desired medium

Docker version 17.03.1-ce, build c6d412e

I can confirm this behaviour for different host systems (ubuntu, gentoo; dedicated hardware, AWS) with different docker versions, with and without the help of docker-compose.

In order to reproduce this issue it is not necessary to run this image (container) for the whole week. So the simplest way to reproduce may be 
1. create image using the simple example Dockerfile above
2. EXEC into the container and install some package (e.g. tree or whatever)
3. shutdown container
4. wait a week
5. start the container (without re-creating the whole image, of course)
6. EXEC into the container and do an INSTALL or REFRESH + INSTALL

I can provide you with more information regarding this issue. What do you need?

Thanks in advance!

**Comment by flavio** [comment] 2017-05-15 13:59
Are you refreshing the repositories metadata before doing the `zypper in` operation? tumbleweed packages change very often, you are probably trying to download an older version of the package which is no longer available.

**Comment by realknorke** [comment] 2017-05-15 15:22
When the package that wants to be installes is no longer available, why does a RETRY work?

Apart from this question I double-checked whether or not a REFRESH helps to avoid the problem. It doesn't.

> bash-4.4# tree           
bash: tree: command not found
bash-4.4# zypper install tree
Retrieving repository 'NON-OSS' metadata [done]
Retrieving repository 'OSS' metadata [done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...
>
>The following NEW package is going to be installed:
  tree
>
>1 new package to install.
Overall download size: 53.8 KiB. Already cached: 0 B. After the operation,
additional 105.7 KiB will be used.
Continue? [y/n/? shows all options] (y): 
Retrieving package tree-1.7.0-3.10.x86_64 (1/1),  53.8 KiB (105.7 KiB unpacked)
Media source 'http://download.opensuse.org/tumbleweed/repo/oss/' does not contain the desired medium
>
>Abort, retry, ignore? [a/r/i/? shows all options] (a): 
Problem occurred during or after installation or removal of packages:
Installation aborted by user
>
>Please see the above error message for a hint.
bash-4.4# zypper ref         
Retrieving repository 'NON-OSS' metadata [done]
Retrieving repository 'OSS' metadata [done]
All repositories have been refreshed.
bash-4.4# echo $?
0
bash-4.4# zypper install tree
Retrieving repository 'NON-OSS' metadata [done]
Retrieving repository 'OSS' metadata [done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...
>
>The following NEW package is going to be installed:
  tree
>
>1 new package to install.
Overall download size: 53.8 KiB. Already cached: 0 B. After the operation,
additional 105.7 KiB will be used.
Continue? [y/n/? shows all options] (y): 
Retrieving package tree-1.7.0-3.10.x86_64 (1/1),  53.8 KiB (105.7 KiB unpacked)
Media source 'http://download.opensuse.org/tumbleweed/repo/oss/' does not contain the desired medium
>
>Abort, retry, ignore? [a/r/i/? shows all options] (a): r
Retrieving: tree-1.7.0-3.10.x86_64.rpm [done]
Checking for file conflicts: [done]
(1/1) Installing: tree-1.7.0-3.10.x86_64 [done]
bash-4.4#

**Comment by realknorke** [comment] 2017-05-15 15:23
maybe this is of interest (taken from one of my older tumbleed containers -- but I can reproduce the problem even on "latest" images)
 
> bash-4.4# zypper lr -d  
Repository priorities are without effect. All enabled repositories share the same priority.
>
> \# | Alias   | Name    | Enabled | GPG Check | Refresh | Priority | Type  | URI                                                   | Service
--+---------+---------+---------+-----------+---------+----------+-------+-------------------------------------------------------+--------
1 | non-oss | NON-OSS | Yes     | (r ) Yes  | Yes     |   99     | yast2 | http://download.opensuse.org/tumbleweed/repo/non-oss/ |        
2 | oss     | OSS     | Yes     | (r ) Yes  | Yes     |   99     | yast2 | http://download.opensuse.org/tumbleweed/repo/oss/     |        
bash-4.4# zypper --version
zypper 1.13.20

**Comment by realknorke** [comment] 2017-05-15 15:26
I also tried `zypper ref -f -b -d` -- problem still exists.

**Comment by flavio** [comment] 2017-05-15 16:29
This is really strange, maybe it could be a mirror related issue? I'll try to reproduce it

**Comment by realknorke** [comment] 2017-05-16 06:28
I tried to read the temp files zypper/libzypper creates when handling with metadata (from repo server) but unfortunately the files are getting deleted too fast. That is, when the error messaged is written to stdout the temp files are already gone. I can see the files using 'strace' though. Maybe I can copy the temp files' content using some inotify hack ("copy all files on close" or stuff like that). 

But I'd like to hear from other people that my problem is reproducible first.

**Comment by vrothberg** [comment] 2017-05-16 08:28
@realknorke I  try to reproduce as well. You already mentioned that it happens on different hosts, but did you observe the issue over a longer period of time? I am asking as there have been some downtime of openSUSE's infrastructure from Friday to Monday.

**Comment by realknorke** [comment] 2017-05-16 08:41
@vrothberg Yes, this issue is not related to the auth/hack issues lately. And with repo/metadata/mirror servers down a RETRY in zypper shouldn't work either.

I posted a description (in German language) in [OpenSUSE Forum](https://www.opensuse-forum.de/thread/38339-tumbleweed-probleme-bei-install-update-media-source-%E2%80%A6-does-not-contain-the-desir/) on 2017-03-31

**Comment by vrothberg** [comment] 2017-05-22 11:55
I couldn't reproduce it until now. We're on it!

**Comment by realknorke** [comment] 2017-05-23 08:49
Hmmm. Which storage driver you're using? I'm using "overlay" -> OverlayFS. (*not* overlay2)

**Comment by vrothberg** [comment] 2017-05-23 08:52
I am using btrfs.

**Comment by realknorke** [comment] 2017-05-23 09:00
Okay. I could (again) confirm the issue using overlay. I created another container using the same Dockerfile but with "overlay2" storage driver. I will test "btrfs" after that (in case the problem still exists with "overlay2"). I'll keep you posted. Please remain this issue open. Thanks. ;)

**Comment by vrothberg** [comment] 2017-05-23 09:09
Great, thanks! I'll do the same with overlay2.

**Comment by realknorke** [comment] 2017-05-29 07:24
Issue confirmed with storage driver "overlay2". I'm testing "devicemapper" driver now. (sadly, no btrfs in use here)

**Comment by realknorke** [comment] 2017-06-12 06:20
Finally, a ray of hope. ;)
I can NOT reproduce the problem when using device mapper as storage backend.

Seems related to overlay/overlay2 only. 
@vrothberg can you reproduce the problem using overlay2?

**Comment by realknorke** [comment] 2017-06-19 11:24
@flavio could you please check if this issue is caused by overlay/overlay2 storage backend? Is zypper/libzypper using unix domain sockets? I read overlay doesn't support this kind of (pseudo)file.

**Comment by flavio** [comment] 2017-06-20 07:11
I'm kinda busy right now, @vrothberg can you take care of that please?

**Comment by vrothberg** [comment] 2017-06-20 07:16
@flavio roger that. @realknorke, sorry for the longer silence. I've been quite busy the last weeks and simply didn't find time to check your issue.  Now I have more time and will look into it right now.

**Comment by realknorke** [comment] 2017-06-20 07:58
I really appreciate that. Thank you very much, guys!

**Comment by vrothberg** [comment] 2017-06-20 09:23
@realknorke Could you check your logs after the error occurred? I just set up a VM with ext4 to check docker with overlay2, and am trying to reproduce, so in the meantime we could dig a little deeper into your setup.

I stumbled across https://github.com/docker/docker/issues/10180 and I see some similarities to your issue. The mentioned issue is caused by data inconsistencies when simultaneously reading RO and writing to the same file. Overlay seems to have problems syncing the data among the different layers and the container layer.

**Comment by realknorke** [comment] 2017-06-20 13:55
@vrothberg in which log exactly? I will attach all necessary logs. Nothing interesing in kernel ring buffer (dmesg) or docker syslog.

The simple test to reproduce the bug doesn't work here: opening two file handles with RDONLY and RDWR and then write to the RDWR handle and read from the RDONLY handle. The result is as expected (seeing the written data from the RDWR handle).

I think it is much more difficult to reproduce the issue in a minimal environment. From the linked issue 10180 I'm trying to play around with the /sys/module/overlay/parameters/check_copy_up pseudo file. This setting is always set to N. I'm trying to reproduce my issue when check_copy_up is set to Y.

Overall it seems that the CentOS guys wrote some kind of workaround (copying or touching important files before reading from RDONLY file handle or whatever). I'll look into this matter deeper tomorrow or the day after tomorrow. For now I set up another (brand new) overlay2-backed tumbleweed base image and now wait some days to play around with sysfs' check_copy_up…

**Comment by vrothberg** [comment] 2017-06-21 05:49
Thanks, @realknorke! The interesting log would have been dmesg. I setup an image yesterday and will try to reproduce it over time.

One thing I'd love to check is when removing the affected repository from */etc/zypp/repos.d* and then running a `$zypper in tree`.

**Comment by vrothberg** [comment] 2017-06-26 12:50
I am checking daily to reproduce the issue, still without success :-( Let's keep an eye on it.

**Comment by realknorke** [comment] 2017-06-26 13:04
The only message in log when starting docker is

> Jun 26 14:54:53 [kernel] cgroup: docker-runc (23631) created nested cgroup for controller "memory" which has incomplete hierarchy support. Nested cgroups may change behavior in the future.
Jun 26 14:54:53 [kernel] cgroup: "memory" requires setting use_hierarchy to 1 on the root

Setting 'check_copy_up' to 'Y' in sysfs doesn't help.

When removing the affected repo (which is installed by default and no. 2 in the following "zypper lr -d" output) I cannot install the 'tree' package, because "No provider of 'tree' found."

> 1 | non-oss     | NON-OSS     | Yes     | (r ) Yes  | Yes     |   99     | yast2  | http://download.opensuse.org/tumbleweed/repo/non-oss/ |        
2 | oss         | OSS         | Yes     | (r ) Yes  | Yes     |   99     | yast2  | http://download.opensuse.org/tumbleweed/repo/oss/     |

**Comment by vrothberg** [comment] 2017-06-26 13:32
I'll look into the source of the logs.

> When removing the affected repo (which is installed by default and no. 2 in the following "zypper lr -d" output) I cannot install the 'tree' package, because "No provider of 'tree' found."

I assumed your observations are unrelated to the package, but to the repository. There's at least one package in `non-oss` you could try to install `iozone`.

**Comment by vrothberg** [comment] 2017-06-27 13:47
Could run `zypper in tree` with `-vvv` and post the output here? I am reading zypper and libzypp code to get a better understanding of what's happening there.

**Comment by realknorke** [comment] 2017-06-27 15:25
@vrothberg hmm I think you cannot reproduce it then. The problem happens after a few days (like 4-7 days or so) with 100% success rate on my Gentoo machines as well as Ubuntu (LTS) machines on Amazon AWS.
But only with overlay and overlay2 storage driver. I cannot reproduce the problem with device-mapper storage driver. And my assumption is that btrfs, aufs and zfs as storage backend work well, too.

Give me some days, I'll try to delete the official repo and then install iozone from the update repo as you requested. I'll send a comment then.

**Comment by realknorke** [comment] 2017-06-28 07:02
@vrothberg I can install iozone from the 'non-oss' repository. No problem here.

I tried another package from non-oss: 'xv'. Its only in non-oss but has deps in 'oss'. Same problem: cannot install dependencies from 'oss' repo. After removing oss-repo and installing 'xv' (accepting broken deps) everything works (the installation) fine.

BUT
Before I install something (no matter which package) I see the message:
> Retrieving repository 'OSS' metadata  ..... [done]

Always! Even when I install 'iozone' which is in 'non-oss' and does NOT have any deps in 'oss'.
I don't see a message like 'retrieving repo NON-OSS metadata'! Is this okay?

Update: Doing 'zypper ref -f -b' doesn't change a thing.

**Comment by vrothberg** [comment] 2017-06-28 07:21
> Always! Even when I install 'iozone' which is in 'non-oss' and does NOT have any deps in 'oss'. I don't see a message like 'retrieving repo NON-OSS metadata'! Is this okay?

It looks suspicious, but I have only limited knowledge of zypper. Did you remove the repo by hand or via `zypper rr`? What could speed-up debugging is to do a `docker commit` on a "broken" container and use that image afterwards. If there's nothing confidential you could push that to docker hub and we can go from there.

**Comment by realknorke** [comment] 2017-06-28 08:06
@vrothberg  I used "zypper rr" to remove the repo. 
I uploaded the broken container to docker hub: knorke/tumbleweed-base-debug

Are you using overlay or overlay2 at the moment?

**Comment by realknorke** [comment] 2017-06-28 08:25
The message in dmesg 'cgroup: "memory" requires setting use_hierarchy to 1 on the root' (see above, 2 days ago) is not related to the problem. I set /sys/fs/cgroup/memory/memory.use_hierarchy to 1 (was 0) and the message on docker startup is now gone but the problem is still present.

**Comment by vrothberg** [comment] 2017-06-28 08:32
> I uploaded the broken container to docker hub: knorke/tumbleweed-base-debug

Thanks a lot.

> Are you using overlay or overlay2 at the moment?

Yes, I have a clean Leap VM with ext4 and overlay2 running.

**Comment by realknorke** [comment] 2017-06-28 09:26
@vrothberg I installed Leap in VirtualBox (server flavor with ext4) and tested my debug image with docker-compose. I can reproduce the problem within Opensuse Leap host system (host for docker, guest in VBox)

**Comment by vrothberg** [comment] 2017-06-29 06:46
@realknorke Can you try it with `docker pull` and `docker run` instead of `docker-compose`? I just did that and the error didn't occur in my Leap 42.2 VM with ext4 and overlay2.

**Comment by realknorke** [comment] 2017-06-29 11:46
@vrothberg I used docekr pull && docker run. Same problem.
Tested it in my 42.2 LEAP VirtualBox VM (NetInstall with ext4 and overlay2).

Do we really have to exchange VM images now?
I created an snapshot directly after triggering the bug.

Could you reproduce the bug with MY virtual machine on YOUR workstation? (I hope it is possible to simply move and start VMs like that)
I'm using VBox 5.0.32 on a Intel i7-4790K.
I took the directory 'leap' from ~/.VirtualBox/Machines/

DL link for VM with snapshot 'bug': https://drive.google.com/drive/folders/0B9ZKlmZ8YOXBX1FsaElfc0VyYlE?usp=sharing
(caution! 1.6gb!)

In case you can restore the snapshot "bug" you'll see the error message (console 1 and 2 are used) and how I reproduced it. I deleted all other containers and images first.

**Comment by vrothberg** [comment] 2017-06-29 11:54
> DL link for VM with snapshot 'bug': 

I don't see any file in this folder. Are you still uploading?

**Comment by realknorke** [comment] 2017-06-29 12:03
Yep, sorry, I was too fast with my comment. Upload is finished now.

**Comment by vrothberg** [comment] 2017-06-29 12:40
No problem. Can you provide the root password?

**Comment by realknorke** [comment] 2017-06-29 12:52
sorry. I added a user named 'knorke' with pw 'lamer123'. The pw for root is the same.

**Comment by vrothberg** [comment] 2017-06-30 11:40
Some updates from debugging.

The issue seems to be that the curled media file is either corrupted or absent when checking if it's the desired media. To be more specific `bool SUSEMediaVerifier::isDesiredMedia(const media::MediaAccessRef &ref)` in [1] doesn't succeed. I suspect some race condition in overlay or even a bug. I double-checked with the zypper maintainer to make sure the CPP warning doesn't have a history. I'll patch libzypp to provide some more logs and see what's going on in this specific case.

Thanks @realknorke for providing everything.

[1] https://github.com/openSUSE/libzypp/blob/master/zypp/repo/SUSEMediaVerifier.cc

**Comment by realknorke** [comment] 2017-06-30 12:27
No,
thank YOU for your patience! ;)

**Comment by vrothberg** [comment] 2017-07-01 13:08
Some patched version of `libzypp` revealed that the ID of the cached media file is different to the one in the Tumbleweed repository. A `zypper clean -M` helps to fix the problem as it cleans the raw  metadata. I continue digging as it ultimately seems like a filesystem issue, but I'm also unhappy with zypper. 

As @realknorke described, the installation succeeds when retrying, but installing another package afterwards fails again with the same error. I deduce that zypper doesn't clean the raw metadata, which it (most likely) should do. At least after retry.

**Comment by vrothberg** [comment] 2017-07-04 11:52
@realknorke, we finished analyzing the issue and provided a fix for zypper here https://github.com/openSUSE/libzypp/pull/72.

The root cause of the symptom you described in this issue is that OverlayFS doesn't (fully) support the `rename(2)` syscall and will fail when src and destination path are not on the same layer. This is exactly the case here as zypper downloads some metadata to check if the cache has to be rebuilt. As the rename fails, zypper keeps the old cache (including the old media file), finally leading to the exception we see here. This also happens on Leap images, but we just don't see the error as Tumbleweed is released on a (nearly) daily basis.

I will close this issue as soon as the PR for `libzypp` is merged.

Cc: @flavio, @mlandres

**Comment by realknorke** [comment] 2017-07-04 11:58
@vrothberg awesome! thanks a lot!

No I'm able to use openSUSE over awful ubuntu in my company.

As soon as this bug gets closed I will delete the files/images I provided. If you need the image and VBox data for later please just say so.

Thanks.

**Comment by vrothberg** [comment] 2017-07-04 12:40
> No I'm able to use openSUSE over awful ubuntu in my company.

Sounds awesome, have fun :-) Just be aware that OverlayFS can let other applications break as well. But if you have control over the deployments, it *should* be fine. Until the PR has been merged and made it to the package, I suggest to run `zypper clean -M` before updating, installing, etc.

> As soon as this bug gets closed I will delete the files/images I provided. If you need the image and VBox data for later please just say so.

Thanks a lot, feel free to delete them.

**Comment by vrothberg** [comment] 2017-07-04 13:04
The fix is now merged to `libzypp` in https://github.com/openSUSE/libzypp/pull/72. Closing the issue.

**Closed as completed by vrothberg** 2017-07-04 13:04 UTC
Labels: bug
